---
- name: Set authorized key for base rasbpi user
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Change default unix password
  user:
    name: pi
    password: "{{ unix_password | password_hash('sha512') }}"

- name:
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}|raspberrypi')
  register: hostname

- name: Ensure hostname is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}.+$"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
  register: hostname
  tags: hostname

- name: set timezone to UTC
  timezone:
    name: UTC
  register: timezone

- name: gpu mem check
  shell: cat /boot/config.txt | grep gpu_mem | cat
  changed_when: false
  register: gpu_mem_check

- name: reduce gpu memory
  lineinfile:
    path: /boot/config.txt
    line: gpu_mem=16
  register: gpu_mem
  when: gpu_mem_check.stdout == ""

- name: Enabling cgroup options at boot
  copy:
    src: cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: 0755
  register: cmdline
  tags:
    - boot

- name: python-apt dependency
  apt:
    name: python-apt
    state: present

- name: apt-get update
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: apt-get upgrade
  apt:
    upgrade: full

- name: Reboot as needed
  reboot:
    reboot_timeout: 3600
  when: (cmdline is changed) or
        (timezone is changed) or
        (gpu_mem is changed) or
        (hostname is changed)
